### ISSUE TITLE
build fails because of missing nng dependency

### ISSUE THREAD

**Issue by stefanKnott** [Comcast/parodus2mockTr181#18]
When trying to build this project, it fails because of missing nng as a dependency of libparodus.

**Comment by stefanKnott** [comment]
PR: https://github.com/Comcast/parodus2mockTr181/pull/19

**Comment by stefanKnott** [comment]
Link to PR: https://github.com/Comcast/parodus2mockTr181/pull/20

As a note..it seems you all may need to update the version of cmake on the box you are running Travis build on.  All tests and builds work correctly for me using an updated cmake version.

**Comment by shilpa24balaji** [comment]
@stefanKnott thanks for the PR, we will check it.

**Comment by shilpa24balaji** [comment]
This is fixed as part of PR: #21
